#Attendance.R

library(openxlsx)

#ADA_Value_Code (ver4.0.0) Float ADA value for this day, student combination based on daily codes. 
#ADA_Value_Time (ver4.0.0) Float ADA value for this day, student combination for time mode. 
#ADM_Value (ver4.0.0) Float ADM value for this day, student combination.   
#Att_Comment (ver4.0.0) CLOB Free form text that staff can enter for this attendance record. 
#Att_Date (ver4.0.0) Date This is the date the attendance was taken for this record. Although a relationship to Calendar_Day exists, this is done for performance reasons. Indexed.  
#Att_Flags (ver5.0.0) Number(10,0) Multi-use field, which is currently used to track the "origin" of this record.   
#Att_Interval (ver4.0.0) Number(10,0) For Time attendance, the interval in the section that attendance being taken. For example, if 4-hour section attendance could be taken 4 times and this would be the instance 1 or 2. Indexed.  
#Att_Mode_Code (ver4.0.0) Varchar(20) Classification of attendance records: section, daily, hbyh, and hbyday. Indexed. 
#Attendance_CodeID (ver4.0.0) Number(10,0) The internal number for the Parent Attendance with which this record is associated. This shows if this row is linked to another in this table, such as backfilling purposes. Indexed.
#CCID (ver4.0.0) Number(10,0) The internal number for the CC with which this record is associated. Indexed.   
#Calendar_DayID (ver4.0.0) Number(10,0) The internal number for the Calendar Day with which this record is associated. Indexed. 
#DCID (ver4.0.0) Number(10,0) Unique identifier for this table. Indexed. Required.   
#ID (ver4.0.0) Number(10,0) Sequential number generated by the application, but uniqueness in the table is not guaranteed. Indexed.   
#IP_Address (ver7.8.0) Varchar(39) The IP address of the machine creating or updating the attendance row. Note: Compatible with Ipv6 format.  
#Lock_Reporting_YN (ver4.0.0) Number(10,0) Indicates whether attendance can be changed due to reporting. 
#Lock_Teacher_YN (ver4.0.0) Number(10,0) Indicates whether teacher can change attendance or not. 
#Parent_AttendanceID (ver4.0.0) Number(10,0) The attendance record this record is linked to. Mainly for backfilling purposes to see where the record those hours were debited from are. Indexed.
#PeriodID (ver4.0.0) Number(10,0) The internal number for the Period with which this record is associated. Indexed.   
#ProgramID (ver4.0.0) Varchar(80) Program under which attendance is taken. Indexed.   
#Prog_Crse_Type (ver4.0.4) Varchar(10) Program Course Type. 
#PSGUID (ver7.8.0) Varchar(50) If used, a unique identifier for the row. Currently applicable to multi-tenant, Schoolnet, and Pearson SuccessNet/Pearson SuccessNet Plus.   
#SchoolID (ver4.0.0) Number(10,0) The School_Number of the associated Schools record.   
#StudentID (ver4.0.0) Number(10,0) The internal number and ID of the associated Students record.   
#Total_Minutes (ver4.0.0) Number(10,0) Total minutes of attendance for this record, can be negative in the case of a debit transaction for backfilling. 
#Transaction_Type (ver4.0.0) Varchar(10) Indicates credit or debit for this record. This is mainly used for backfilling purposes where attendance hours is debited from one record and credited into another.
#WhoModifiedID (ver7.8.0) Number(10,0) The DCID of the associated Users record unless the default is applied. Defaults to 0. For example, if WhoModifiedType = s, then this value is Students. DCID. However, if WhoModifiedType = u or ?, then this value is 0.
#WhoModifiedType (ver7.8.0) Varchar(1) Indicates the type of user that modified the record. Valid values: a = admin, t = teacher, p = parent, s = student, u = substitute, m = maintenance, ? = unknown.
#YearID (ver4.0.0) Number(10,0) A number representing which year the term belongs to, such as 13 for 2003-2004. The number is equal to the ID of the year term divided by 100. Maintained in the Terms table. Indexed.  



d1 = read.xlsx("attendance_export.xlsx", "Att")
d2 = read.xlsx("attendance_export.xlsx", "AttendanceCodes")
d1$Desc = d2$Description[match(d1$Attendance_CodeID, d2$ID)]
students = data.frame(studentNumber = unique(d1$`[1]Student_Number`))
students$name = d1$`[1]LastFirst`[match(students$studentNumber,d1$`[1]Student_Number`)]
statuses = unique(d1$Desc[d1$Att_Mode_Code == "ATT_ModeMeeting"])

for(i in statuses){
  students[,i] = NA_integer_
}

for(i in 1:nrow(students)){
  for(j in statuses){
    students[i,j] = sum(d1$`[1]Student_Number` == students$studentNumber[i] & d1$Desc == j & d1$Att_Mode_Code == "ATT_ModeMeeting")
  }
}




summary(students[,3:12])


students[students$`ISS Absent unexcused` > 100,]

unique(d1$`[1]LastFirst`[d1$Desc == "Expelled"])


str(students)



write.csv(x = students[order(students$`Absence Unexcused`, decreasing = T),1:3], file = "attendance_issues.csv")



